### ISSUE TITLE
Additional relays

### ISSUE THREAD

**Issue by JustinDrake** [samfedenia/flashbots_systemd_service#1]
Consider adding more relays to https://github.com/samfedenia/flashbots_systemd_service/blob/main/relay-config.env

For example relay.ultrasound.money and agnostic-relay.net :)

**Comment by samfedenia** [comment]
will do! thank you

**Comment by samfedenia** [comment]
done!

**Comment by JustinDrake** [comment]
That was fast! I think you need to add the full addresses:

`https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money`

and

`https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money`

**Comment by samfedenia** [comment]
ah I see, should have double checked that. Thanks!
